fragment CartFields on Cart {
    entityId
    amount {
        ...MoneyFields
    }
    createdAt {
        utc
    }
    currencyCode
    locale
    lineItems {
        totalQuantity
        customItems {
            quantity
            entityId
            extendedListPrice {
                ...MoneyFields
            }
            listPrice {
                ...MoneyFields
            }
            name
            sku
        }
        totalQuantity
        physicalItems {
            brand
            quantity
            entityId
            variantEntityId
            extendedListPrice {
                ...MoneyFields
            }
            listPrice {
                ...MoneyFields
            }
            name
            sku
            productEntityId
            couponAmount {
                ...MoneyFields
            }
            image {
                url320wide: url(width: 320)
                url640wide: url(width: 640)
                url960wide: url(width: 960)
                url1280wide: url(width: 1280)
            }
            selectedOptions {
                entityId
                name
                ... on CartSelectedMultipleChoiceOption {
                    name
                    value
                    entityId
                    valueEntityId
                }
            }
        }
        digitalItems {
            brand
            quantity
            entityId
            variantEntityId
            extendedListPrice {
                ...MoneyFields
            }
            listPrice {
                ...MoneyFields
            }
            name
            sku
            entityId
            productEntityId
            couponAmount {
                ...MoneyFields
            }
            image {
                url320wide: url(width: 320)
                url640wide: url(width: 640)
                url960wide: url(width: 960)
                url1280wide: url(width: 1280)
            }
            selectedOptions {
                entityId
                name
            }
        }
    }
}